# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: scanmatcher_frame
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  width: 10.0
  height: 10.0
